### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by rangergx** [rangergx/protospace-38241#1]
#URL
https://protospace-38241.herokuapp.com/

**Comment by motomuun** [comment]
@rangergx さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
**コメント機能**

- [ ] **フォームを空のまま投稿しようとすると、投稿できずにそのページに留まること**
空欄のまま投稿が出来てしまいます。空欄の場合は投稿できないように修正をお願いします。


修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by motomuun** [comment]
@rangergx さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、前回依頼した箇所の修正が出来ておりませんでした。
今一度ご確認をお願いします。

[修正依頼箇所]
**コメント機能**

- [ ]  **フォームを空のまま投稿しようとすると、投稿できずにそのページに留まること**
空欄のまま投稿が出来てしまいます。空欄の場合は投稿できないように修正をお願いします。
<img width="1437" alt="スクリーンショット 2022-08-04 11 28 46" src="https://user-images.githubusercontent.com/65059944/182750422-30872370-8852-4de0-bdc3-14fc174bd734.png">


修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by snkw-works** [comment]
@rangergx さん、修正とご提出ありがとうございます‼︎
正常に動作することが確認できました！　**LGTM**です✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
